- App.tsx
- app.d.ts
- babel.config.js
- components/ContentWrapper.tsx
- enums/routes.ts
- package-lock.json
- package.json
- screens/Home/Home.tsx
- screens/Login/Login.tsx
- tailwind.config.js
- types/navigation.ts
- Setup TailwindCSS (NativeWind)
- React Native Navigation
- Typescript boilerplate (Types, Enums)
- Setup Style Guide for doing Components and functions
> [Setup][Ezra] boilerplate setup

- components/ContentWrapper.tsx
- components/Header.tsx
- components/Search.tsx
- screens/Home/Home.tsx
- tailwind.config.js
Add header component for `home` page
> [Feature][Hans] add header component

- .eslintrc.json
- components/FeatureCarousel.tsx
- components/Header.tsx
- components/Search.tsx
> [Fix][Ezra] eslint rules

- components/Header.tsx
- components/Search.tsx
- components/icons/BagIcon.tsx
- components/icons/SearchIcon.tsx
- components/icons/index.ts
- package-lock.json
- package.json
Align Header UI with figma design
> [Enhancment][Hans] improve header ui

- components/carousel/FeatureCarousel.tsx
- components/carousel/ProductsCarousel.tsx
- data/products.ts
- enums/categories.ts
- enums/db.ts
- firebase/storage.ts
- helpers/upload.ts
- package-lock.json
- package.json
- screens/Sell/AddPhoto.tsx
- screens/Sell/ProductDescription.tsx
- screens/Sell/Sell.tsx
- types/product.ts
**Missing**
- Input validation (All fields inputted, price is valid)
> [Feature][Ezra] post product integration

- App.tsx
- components/Header.tsx
- components/Icons/EmojiIcon.tsx
- components/product-page-components/SpecificProductCarousel.tsx
- enums/routes.ts
- screens/Chat/Chat.tsx
- screens/SpecificProduct/ProductCarousel.tsx
- screens/SpecificProduct/SpecificProduct.tsx
- types/navigation.ts
data, types, screen file and components for specific product page.
> [Feature][Franz] Specific Product Page UI

- components/FullScreenLoading/Product.tsx
- components/FullScreenLoading/index.ts
- enums/routes.ts
- screens/SpecificProduct/ProductCarousel.tsx
- screens/SpecificProduct/SpecificProduct.tsx
- types/navigation.ts
refer to messenger gc for the ui
> [Feature][Ezra] specific product integration

- components/ContentWrapper.tsx
- components/StatusBarStyle.tsx
- components/modals/MenuModal.tsx
- screens/Home/Home.tsx
- screens/Login/Login.tsx
- screens/ProductListings/ProductListings.tsx
- screens/Sell/Sell.tsx
> [UI] [Louie] Status Bar Visibility

- screens/Login/Login.tsx
- screens/SpecificProduct/SpecificProduct.tsx
https://github.com/ezerssss/unihub/assets/124412484/9b6f7a1e-628f-403c-84eb-34b621497c9c
https://github.com/ezerssss/unihub/assets/124412484/08e6e22e-ed7f-4d8d-983a-d8dec5276c60
> [UI] [Sam] UI Improvements (Login, Product Page)

- components/carousel/FeatureCarousel.tsx
> [UI] [Louie] Feature Carousel changes

- App.tsx
- components/carousel/CategoriesCarousel.tsx
- components/carousel/ProductsCarousel.tsx
- enums/routes.ts
- screens/Category/Category.tsx
- screens/Category/CategorySwiper.tsx
- types/navigation.ts
UI Change:
In Product Carousel changed PHP > ₱
Screen:
Category Screen + Swiper Component
Linked Category Carousel Buttons to Category Page
Edited Navigation Files
> [SAM][UI] Category Screen & Navigation + UI Change

- components/AuthWrapper.tsx
- components/Header.tsx
- enums/db.ts
- helpers/auth.ts
- screens/SpecificProduct/BuyConfirmation.tsx
- screens/SpecificProduct/SpecificProduct.tsx
- types/navigation.ts
- types/transaction.ts
- types/user.ts
This PR adds the transaction object to the buyer, seller, and creates a new transaction collection
> [Feature][Hans] add transaction object

- App.tsx
- components/carousel/CategoriesCarousel.tsx
- data/category.ts
- enums/categories.ts
- screens/Category/Category.tsx
- screens/Category/CategorySwiper.tsx
- types/category.ts
- types/navigation.ts
- types/product.ts
-still havent done all products, requires all products button on product carousel(blocker), doing it tomorrow
https://github.com/ezerssss/unihub/assets/90561528/deed22c7-02f7-4f55-93fb-3f70170b72e8
> [Feature] [Louie] Categorized products integration

- App.tsx
- screens/Home/Home.tsx
- screens/Login/Login.tsx
Clickup task: https://app.clickup.com/t/865ckb8pk
- Adjust login loading feedback
- Clean route priority
> [Adjustment][Ezra] login loading and route cleaning

- App.tsx
- enums/routes.ts
- screens/SpecificProduct/ProductSold.tsx
- types/navigation.ts
Clickup Task: https://app.clickup.com/t/865cjuu8k
- Still not sure where to connect this page
> [UI] [Louie] Product Sold Page

- App.tsx
- components/Header.tsx
- components/progressbar/ProgressBar.tsx
- enums/routes.ts
- enums/status.ts
- screens/Chat/Chat.tsx
- screens/Chat/TransactionButton.tsx
- screens/SpecificProduct/BuyConfirmation.tsx
- screens/SpecificProduct/SpecificProduct.tsx
- screens/Transactions/StatusText.tsx
- screens/Transactions/Transactions.tsx
- types/navigation.ts
- types/transaction.ts
ill do a demonstration nalang laters
> [Feature][Ezra] buy integration complete

- components/modals/MenuModal.tsx
- package-lock.json
- package.json
changed avatar to render svg images and fixed inconsistency
according to user request
+ dicebear deps
> [enhancement][Jerome] change avatar provider

- App.tsx
- components/Header.tsx
- components/Search.tsx
> [enhancement][Jerome] enhanced search bar size

- App.tsx
- screens/Login/Login.tsx
https://app.clickup.com/t/865cm253w
> [Adjustment][Ezra] not allow to back to login

- screens/Chat/Chat.tsx
Clickup Task: https://app.clickup.com/t/865ckb9p6
-might need to double check on android if it still works and on other ios phones
https://github.com/ezerssss/unihub/assets/90561528/c0277ef2-d866-48b7-bf4c-f95a1e3c4e67
> [Adjustment] [Louie] Keyboard Chat Cover Fix

- screens/Sell/Sell.tsx
- screens/SpecificProduct/BuyConfirmation.tsx
https://app.clickup.com/t/865cmaa86
> [Adjustment][Ezra] handle back in order status

- screens/SpecificProduct/SpecificProduct.tsx
> [Adjustment][Ezra] see more and buy button

- screens/SpecificProduct/SpecificProduct.tsx
ClickUp Task: https://app.clickup.com/t/865cn5vj5
https://github.com/ezerssss/unihub/assets/124412484/0907fea3-4564-4258-8516-f6a20032b108
> [Sam][Adjustment] Buying Confirmation Alert

- components/progressbar/ProgressBar.tsx
- constants/products.ts
- enums/status.ts
- helpers/error.ts
- helpers/status.ts
- helpers/upload.ts
- screens/Category/CategorySwiper.tsx
- screens/Chat/Chat.tsx
- screens/Chat/TransactionButton.tsx
- screens/Home/Home.tsx
- screens/Login/Login.tsx
- screens/Sell/Sell.tsx
- screens/SpecificProduct/SpecificProduct.tsx
- screens/Transactions/TransactionStatus.tsx
- services/auth.ts
- services/chat.ts
- services/product.ts
- services/transaction.ts
- Delete Product Photos except for thumbnail when deleting the product
- Cancel all the transactions involving the product except for the successful transaction
- Adjusted the `generateErrorMessage` function to be simpler
Clickup tasks:
- https://app.clickup.com/t/865cn5ppe
- https://app.clickup.com/t/865cn5txw?comment=90080038796322
> [Adjustment][Ezra] delete product photos and cancel all transactions

- screens/Sell/Sell.tsx
- services/product.ts
Subtask: https://app.clickup.com/t/865cn5ty7
- Sell confirmation
- No sell duplication 
https://github.com/ezerssss/unihub/assets/90561528/e54e3813-5437-405d-b7c1-98abe8a078ac
> [Feature] [Louie] Selling additions

- screens/Sell/Sell.tsx
- tailwind.config.js
Clickup Subtask: https://app.clickup.com/t/865cncm1v
- Update existing product still not done
> [Adjustment] [Louie] Sell UI changes

- services/product.ts
- services/transaction.ts
To update  the product just call the `updateProduct` service function.
Task: https://app.clickup.com/t/865cn5wjc
> [Feature][Ezra] update product service function

- screens/SpecificProduct/ProductCarousel.tsx
- screens/SpecificProduct/SpecificProduct.tsx
> [Adjustment][Ezra] swiper bug

- components/OrderConfirmationFooter/footer.tsx
- components/progressbar/ProgressBar.tsx
- screens/SpecificProduct/BuyConfirmation.tsx
Clickup Task: https://app.clickup.com/t/865cnk2ac
> [Adjustment] [Louie] Order Update UI

- components/carousel/CategoriesCarousel.tsx
- components/carousel/ProductsCarousel.tsx
- constants/color.ts
- data/category.ts
- data/colleges.ts
- package-lock.json
- package.json
- screens/Home/CollegeSelector.tsx
- screens/Home/GetFeatured.tsx
- screens/Home/Home.tsx
- screens/Home/TrustedSellers.tsx
Clickup task: https://app.clickup.com/t/865cn5tkq
https://github.com/ezerssss/unihub/assets/124412484/55c4e9ef-9e1f-4079-8ae3-d1cf94f11683
> [UI][Sam] Home UI

- components/icons/ClockIcon.tsx
- components/icons/LocationIcon.tsx
- components/icons/index.ts
- helpers/number.ts
- package-lock.json
- package.json
- screens/Category/Category.tsx
- screens/Category/CategorySwiper.tsx
- screens/Search/Search.tsx
- screens/Search/SecondarySearch.tsx
> [Feature][Hans] Improve category screen UI

- helpers/search.ts
- screens/Category/Category.tsx
- screens/Category/CategorySwiper.tsx
- screens/Search/Search.tsx
- screens/Search/SearchTextResult.tsx
- screens/Search/SecondarySearch.tsx
- services/search.ts
- types/navigation.ts
- types/search.ts
> [Feature][Ezra] category search

- helpers/message.ts
- helpers/search.ts
- helpers/status.ts
- helpers/user.ts
- screens/Category/Category.tsx
- screens/Category/CategorySwiper.tsx
- screens/Chat/Chat.tsx
- screens/Chat/TransactionButton.tsx
- screens/Search/Search.tsx
- screens/Search/SearchTextResult.tsx
- screens/Search/SecondarySearch.tsx
- screens/Transactions/Transactions.tsx
- services/product.ts
- services/search.ts
- services/transaction.ts
- tailwind.config.js
- types/messages.ts
- types/navigation.ts
- types/search.ts
Task: https://app.clickup.com/t/865cn5vr5
> [UI][Sam] Chat Improvement
